load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_test")

rust_binary(
    name = "scrim",
    srcs = glob(["src/**/*.rs"]),
    edition = "2021",
    visibility = ["//visibility:public"],
    deps = all_crate_deps(),
)

rust_test(
    name = "scrim_test",
    crate = ":scrim",
    deps = all_crate_deps(),
)
