module(
    name = "scrim",
    version = "0.1.0",
)

bazel_dep(name = "rules_rust", version = "0.74.0")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2021",
    versions = ["1.85.0"],
)
use_repo(rust, "rust_toolchains")

register_toolchains("@rust_toolchains//:all")

crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
crate.spec(
    features = ["derive"],
    package = "serde",
    version = "1.0",
)
crate.spec(
    package = "serde_yaml",
    version = "0.9",
)
crate.spec(
    package = "serde_with",
    version = "3.0",
)
crate.spec(
    package = "tempfile",
    version = "3.8",
)
crate.spec(
    package = "libc",
    version = "0.2",
)
crate.spec(
    package = "chrono",
    version = "0.4",
)
crate.spec(
    package = "criterion",
    version = "0.5",
)
crate.from_specs()
use_repo(crate, "crates")

bazel_dep(name = "llvm", version = "0.8.19")

register_toolchains("@llvm//toolchain:all")
