load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_test")

rust_library(
    name = "scrim_lib",
    srcs = glob(["**/*.rs"], exclude=["main.rs"]),
    edition = "2021",
    visibility = ["//visibility:public"],
    deps = [
        "@crates//:serde",
        "@crates//:serde_yaml",
        "@crates//:serde_with",
        "@crates//:libc",
        "@crates//:chrono",
        "@crates//:ureq",
        "@crates//:sha2",
        "@crates//:tar",
        "@crates//:flate2",
        "@crates//:zip",
        "@crates//:tempfile",
    ],
)

rust_binary(
    name = "scrim",
    srcs = ["main.rs"],
    edition = "2021",
    rustc_flags = select({
        "//:musl": ["-C", "relocation-model=static"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        ":scrim_lib",
        "@crates//:libc",
        "@crates//:serde_yaml",
    ],
)

rust_test(
    name = "scrim_test",
    crate = ":scrim_lib",
    deps = ["@crates//:tempfile"],
)
